const menu = {
    list() {
        return [
 {
     "backMenu":[
         {
             "child":[
                 {
                     "buttons":[
                         "查看",
                         "新增",
                         "修改",
                         "删除"
                     ],
                     "menu":"管理员管理",
                     "menuJump":"列表",
                     "tableName":"users"
                 }
             ],
             "menu":"管理员管理"
         }
         ,{
             "child":[
                 {
                     "buttons":[
                         "查看",
                         "新增",
                         "删除",
                         "修改"
                     ],
                     "menu":"视频类型管理",
                     "menuJump":"列表",
                     "tableName":"dictionaryFanzhashipin"
                 }
                 ,
                 {
                     "buttons":[
                         "查看",
                         "新增",
                         "删除",
                         "修改"
                     ],
                     "menu":"案例分析类型管理",
                     "menuJump":"列表",
                     "tableName":"dictionaryNews"
                 }
             ],
             "menu":"基础数据管理"
         }
         ,{
             "child":[
                 {
                     "buttons":[
                         "查看",
                         "新增",
                         "修改",
                         "删除"
                     ],
                     "menu":"反诈视频管理",
                     "menuJump":"列表",
                     "tableName":"fanzhashipin"
                 }
                 ,
                 {
                     "buttons":[
                         "查看",
                         "修改",
                         "删除"
                     ],
                     "menu":"反诈视频留言管理",
                     "menuJump":"列表",
                     "tableName":"fanzhashipinLiuyan"
                 }
                 ,
                 {
                     "buttons":[
                         "查看",
                         "删除"
                     ],
                     "menu":"反诈视频收藏管理",
                     "menuJump":"列表",
                     "tableName":"fanzhashipinCollection"
                 }
             ],
             "menu":"反诈视频管理"
         }
         ,{
             "child":[
                 {
                     "buttons":[
                         "查看",
                         "新增",
                         "修改",
                         "删除"
                     ],
                     "menu":"论坛管理",
                     "menuJump":"列表",
                     "tableName":"forum"
                 }
             ],
             "menu":"论坛管理"
         }
         ,{
             "child":[
                 {
                     "buttons":[
                         "查看",
                         "新增",
                         "修改",
                         "删除"
                     ],
                     "menu":"案例分析管理",
                     "menuJump":"列表",
                     "tableName":"news"
                 }
             ],
             "menu":"案例分析管理"
         }
         ,{
             "child":[
                 {
                     "buttons":[
                         "查看",
                         "新增",
                         "修改",
                         "删除"
                     ],
                     "menu":"用户管理",
                     "menuJump":"列表",
                     "tableName":"yonghu"
                 }
             ],
             "menu":"用户管理"
         }
         ,{
             "child":[
                 {
                     "buttons":[
                         "查看",
                         "新增",
                         "修改",
                         "删除"
                     ],
                     "menu":"轮播图管理",
                     "menuJump":"列表",
                     "tableName":"config"
                 }
             ],
             "menu":"轮播图信息"
         }
     ],
     "frontMenu":[],
     "hasBackLogin":"是",
     "hasBackRegister":"否",
     "hasFrontLogin":"否",
     "hasFrontRegister":"否",
     "roleName":"管理员",
     "tableName":"users"
 },
 {
     "backMenu":[
         {
             "child":[
                 {
                     "buttons":[
                         "查看"
                     ],
                     "menu":"反诈视频管理",
                     "menuJump":"列表",
                     "tableName":"fanzhashipin"
                 }
                 ,
                 {
                     "buttons":[
                         "查看",
                         "删除"
                     ],
                     "menu":"反诈视频留言管理",
                     "menuJump":"列表",
                     "tableName":"fanzhashipinLiuyan"
                 }
                 ,
                 {
                     "buttons":[
                         "查看",
                         "删除"
                     ],
                     "menu":"反诈视频收藏管理",
                     "menuJump":"列表",
                     "tableName":"fanzhashipinCollection"
                 }
             ],
             "menu":"反诈视频管理"
         }
         ,{
             "child":[
                 {
                     "buttons":[
                         "查看"
                     ],
                     "menu":"论坛管理",
                     "menuJump":"列表",
                     "tableName":"forum"
                 }
             ],
             "menu":"论坛管理"
         }
         ,{
             "child":[
                 {
                     "buttons":[
                         "查看"
                     ],
                     "menu":"案例分析管理",
                     "menuJump":"列表",
                     "tableName":"news"
                 }
             ],
             "menu":"案例分析管理"
         }
     ],
     "frontMenu":[],
     "hasBackLogin":"是",
     "hasBackRegister":"否",
     "hasFrontLogin":"否",
     "hasFrontRegister":"否",
     "roleName":"用户",
     "tableName":"yonghu"
 }
]
    }
}
export default menu;
